# Generated by Django 2.2 on 2020-08-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=20)),
                ('autor', models.CharField(default='', max_length=20)),
                ('titulo', models.CharField(default='', max_length=20)),
                ('ano', models.IntegerField(null=True)),
                ('status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('correo', models.CharField(default='', max_length=20)),
                ('telefono', models.IntegerField(null=True)),
                ('NumLibros', models.IntegerField(null=True)),
                ('adeudo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Persona')),
                ('matricula', models.IntegerField(null=True)),
            ],
            bases=('App.persona',),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Material')),
                ('editorial', models.CharField(default='', max_length=20)),
            ],
            bases=('App.material',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Persona')),
                ('numEmpleado', models.IntegerField(null=True)),
            ],
            bases=('App.persona',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Material')),
                ('numero', models.IntegerField(null=True)),
            ],
            bases=('App.material',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSalida', models.DateField(auto_now=True)),
                ('fechaRegreso', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Material')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Persona')),
            ],
        ),
    ]
