# Generated by Django 2.2 on 2020-08-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Alumno')),
                ('profesor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='TMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Libro')),
                ('revista', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Revista')),
            ],
        ),
    ]
